/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsProjectIdStatisticsRouteImport } from './routes/_app.projects.$projectId.statistics'
import { Route as AppProjectsProjectIdSimulationRouteImport } from './routes/_app.projects.$projectId.simulation'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/_app.projects.$projectId.settings'
import { Route as AppProjectsProjectIdPromptsRouteImport } from './routes/_app.projects.$projectId.prompts'
import { Route as AppProjectsProjectIdNodesRouteImport } from './routes/_app.projects.$projectId.nodes'
import { Route as AppProjectsProjectIdMarketingRouteImport } from './routes/_app.projects.$projectId.marketing'
import { Route as AppProjectsProjectIdDashboardRouteImport } from './routes/_app.projects.$projectId.dashboard'
import { Route as AppProjectsProjectIdBriefRouteImport } from './routes/_app.projects.$projectId.brief'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdStatisticsRoute =
  AppProjectsProjectIdStatisticsRouteImport.update({
    id: '/projects/$projectId/statistics',
    path: '/projects/$projectId/statistics',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdSimulationRoute =
  AppProjectsProjectIdSimulationRouteImport.update({
    id: '/projects/$projectId/simulation',
    path: '/projects/$projectId/simulation',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdPromptsRoute =
  AppProjectsProjectIdPromptsRouteImport.update({
    id: '/projects/$projectId/prompts',
    path: '/projects/$projectId/prompts',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdNodesRoute =
  AppProjectsProjectIdNodesRouteImport.update({
    id: '/projects/$projectId/nodes',
    path: '/projects/$projectId/nodes',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdMarketingRoute =
  AppProjectsProjectIdMarketingRouteImport.update({
    id: '/projects/$projectId/marketing',
    path: '/projects/$projectId/marketing',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdDashboardRoute =
  AppProjectsProjectIdDashboardRouteImport.update({
    id: '/projects/$projectId/dashboard',
    path: '/projects/$projectId/dashboard',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdBriefRoute =
  AppProjectsProjectIdBriefRouteImport.update({
    id: '/projects/$projectId/brief',
    path: '/projects/$projectId/brief',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$projectId/brief': typeof AppProjectsProjectIdBriefRoute
  '/projects/$projectId/dashboard': typeof AppProjectsProjectIdDashboardRoute
  '/projects/$projectId/marketing': typeof AppProjectsProjectIdMarketingRoute
  '/projects/$projectId/nodes': typeof AppProjectsProjectIdNodesRoute
  '/projects/$projectId/prompts': typeof AppProjectsProjectIdPromptsRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId/simulation': typeof AppProjectsProjectIdSimulationRoute
  '/projects/$projectId/statistics': typeof AppProjectsProjectIdStatisticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$projectId/brief': typeof AppProjectsProjectIdBriefRoute
  '/projects/$projectId/dashboard': typeof AppProjectsProjectIdDashboardRoute
  '/projects/$projectId/marketing': typeof AppProjectsProjectIdMarketingRoute
  '/projects/$projectId/nodes': typeof AppProjectsProjectIdNodesRoute
  '/projects/$projectId/prompts': typeof AppProjectsProjectIdPromptsRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId/simulation': typeof AppProjectsProjectIdSimulationRoute
  '/projects/$projectId/statistics': typeof AppProjectsProjectIdStatisticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$projectId/brief': typeof AppProjectsProjectIdBriefRoute
  '/_app/projects/$projectId/dashboard': typeof AppProjectsProjectIdDashboardRoute
  '/_app/projects/$projectId/marketing': typeof AppProjectsProjectIdMarketingRoute
  '/_app/projects/$projectId/nodes': typeof AppProjectsProjectIdNodesRoute
  '/_app/projects/$projectId/prompts': typeof AppProjectsProjectIdPromptsRoute
  '/_app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/_app/projects/$projectId/simulation': typeof AppProjectsProjectIdSimulationRoute
  '/_app/projects/$projectId/statistics': typeof AppProjectsProjectIdStatisticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/signup'
    | '/profile'
    | '/settings'
    | '/projects/'
    | '/projects/$projectId/brief'
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId/marketing'
    | '/projects/$projectId/nodes'
    | '/projects/$projectId/prompts'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/simulation'
    | '/projects/$projectId/statistics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/signup'
    | '/profile'
    | '/settings'
    | '/projects'
    | '/projects/$projectId/brief'
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId/marketing'
    | '/projects/$projectId/nodes'
    | '/projects/$projectId/prompts'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/simulation'
    | '/projects/$projectId/statistics'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/signup'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/projects/'
    | '/_app/projects/$projectId/brief'
    | '/_app/projects/$projectId/dashboard'
    | '/_app/projects/$projectId/marketing'
    | '/_app/projects/$projectId/nodes'
    | '/_app/projects/$projectId/prompts'
    | '/_app/projects/$projectId/settings'
    | '/_app/projects/$projectId/simulation'
    | '/_app/projects/$projectId/statistics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/statistics': {
      id: '/_app/projects/$projectId/statistics'
      path: '/projects/$projectId/statistics'
      fullPath: '/projects/$projectId/statistics'
      preLoaderRoute: typeof AppProjectsProjectIdStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/simulation': {
      id: '/_app/projects/$projectId/simulation'
      path: '/projects/$projectId/simulation'
      fullPath: '/projects/$projectId/simulation'
      preLoaderRoute: typeof AppProjectsProjectIdSimulationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/settings': {
      id: '/_app/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/prompts': {
      id: '/_app/projects/$projectId/prompts'
      path: '/projects/$projectId/prompts'
      fullPath: '/projects/$projectId/prompts'
      preLoaderRoute: typeof AppProjectsProjectIdPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/nodes': {
      id: '/_app/projects/$projectId/nodes'
      path: '/projects/$projectId/nodes'
      fullPath: '/projects/$projectId/nodes'
      preLoaderRoute: typeof AppProjectsProjectIdNodesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/marketing': {
      id: '/_app/projects/$projectId/marketing'
      path: '/projects/$projectId/marketing'
      fullPath: '/projects/$projectId/marketing'
      preLoaderRoute: typeof AppProjectsProjectIdMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/dashboard': {
      id: '/_app/projects/$projectId/dashboard'
      path: '/projects/$projectId/dashboard'
      fullPath: '/projects/$projectId/dashboard'
      preLoaderRoute: typeof AppProjectsProjectIdDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/brief': {
      id: '/_app/projects/$projectId/brief'
      path: '/projects/$projectId/brief'
      fullPath: '/projects/$projectId/brief'
      preLoaderRoute: typeof AppProjectsProjectIdBriefRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsProjectIdBriefRoute: typeof AppProjectsProjectIdBriefRoute
  AppProjectsProjectIdDashboardRoute: typeof AppProjectsProjectIdDashboardRoute
  AppProjectsProjectIdMarketingRoute: typeof AppProjectsProjectIdMarketingRoute
  AppProjectsProjectIdNodesRoute: typeof AppProjectsProjectIdNodesRoute
  AppProjectsProjectIdPromptsRoute: typeof AppProjectsProjectIdPromptsRoute
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
  AppProjectsProjectIdSimulationRoute: typeof AppProjectsProjectIdSimulationRoute
  AppProjectsProjectIdStatisticsRoute: typeof AppProjectsProjectIdStatisticsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsProjectIdBriefRoute: AppProjectsProjectIdBriefRoute,
  AppProjectsProjectIdDashboardRoute: AppProjectsProjectIdDashboardRoute,
  AppProjectsProjectIdMarketingRoute: AppProjectsProjectIdMarketingRoute,
  AppProjectsProjectIdNodesRoute: AppProjectsProjectIdNodesRoute,
  AppProjectsProjectIdPromptsRoute: AppProjectsProjectIdPromptsRoute,
  AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
  AppProjectsProjectIdSimulationRoute: AppProjectsProjectIdSimulationRoute,
  AppProjectsProjectIdStatisticsRoute: AppProjectsProjectIdStatisticsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
